# -*- coding: utf-8 -*-
"""assig1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ecYBhGOPou3ozMrPjANsfiJXc3b90BDW
"""

!pip install yfinance

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# choosing stock example "CIB"
ticker = "COMI.CA"

# downloading data during one year
data = yf.download(ticker, start="2025-01-01", end="2025-12-31")

data.head()

#Log Returns
data['Log_Return'] = np.log(data['Close'] / data['Close'].shift(1))

# deleting missing values
data.dropna(inplace=True)

data.head()

# Daily
mean_daily = data['Log_Return'].mean()
std_daily = data['Log_Return'].std()

# Annual
mean_annual = mean_daily * 252
std_annual = std_daily * np.sqrt(252)

# Skewness & Kurtosis
skewness = data['Log_Return'].skew()
kurtosis = data['Log_Return'].kurt()


print("Mean Daily:", mean_daily)
print("Std Daily:", std_daily)
print("Mean Annual:", mean_annual)
print("Std Annual:", std_annual)
print("Skewness:", skewness)
print("Kurtosis:", kurtosis)

plt.figure()
data['Close'].plot(title="Stock Price")
plt.xlabel("Date")
plt.ylabel("Price")
plt.show()

plt.figure()
data['Log_Return'].plot(title="Log Returns")
plt.xlabel("Date")
plt.ylabel("Returns")
plt.show()

plt.figure()
data['Log_Return'].hist(bins=50)
plt.title("Histogram of Log Returns")
plt.xlabel("Returns")
plt.ylabel("Frequency")
plt.show()

if std_annual > 0.3:
    print("The stock is highly volatile")
else:
    print("The stock has low/moderate volatility")

if abs(skewness) < 0.5:
    print("Returns are approximately normal")
else:
    print("Returns are not normally distributed")

if kurtosis > 3:
    print("There are extreme risks (fat tails)")
else:
    print("No significant extreme risks")

tickers = ["COMI.CA", "ETEL.CA", "TMGH.CA"]

for t in tickers:
    data = yf.download(t, start="2025-01-01", end="2025-12-31")
    returns = np.log(data['Close'] / data['Close'].shift(1))
    returns = returns.dropna()

    print(f"\nStock: {t}")
    print("Volatility:", returns.std())

import yfinance as yf
import numpy as np

ticker = "COMI.CA"

data = yf.download(ticker, start="2025-01-01", end="2025-12-31")

# تأكد إن فيه بيانات
print(data.head())

# حساب Log Return
data['Log_Return'] = np.log(data['Close'] / data['Close'].shift(1))

# حذف القيم الناقصة
data.dropna(inplace=True)

# حساب mu و sigma
mu = data['Log_Return'].mean()
sigma = data['Log_Return'].std()

print("mu:", mu)
print("sigma:", sigma)

import numpy as np

S0 = data['Close'].iloc[-1]  # آخر سعر
T = 15
dt = 1

prices = [S0]

for t in range(T):
    Z = np.random.normal()
    S_prev = prices[-1]

    S_next = (
        S_prev
        + mu * S_prev * dt
        + sigma * S_prev * np.sqrt(dt) * Z
        + 0.5 * (sigma**2) * S_prev * dt * (Z**2 - 1)
    )

    prices.append(S_next)

prices

import matplotlib.pyplot as plt

plt.plot(prices)
plt.title("Milstein Stock Price Prediction (15 Days)")
plt.xlabel("Days")
plt.ylabel("Price")
plt.show()

simulations = 100
T = 15
dt = 1

all_paths = []

for i in range(simulations):
    prices = [S0]

    for t in range(T):
        Z = np.random.normal()
        S_prev = prices[-1]

        S_next = (
            S_prev
            + mu * S_prev * dt
            + sigma * S_prev * np.sqrt(dt) * Z
            + 0.5 * (sigma**2) * S_prev * dt * (Z**2 - 1)
        )

        prices.append(S_next)

    all_paths.append(prices)

for path in all_paths:
    plt.plot(path, alpha=0.3)

plt.title("Monte Carlo (Milstein)")
plt.show()

euler_prices = [S0]

for t in range(T):
    Z = np.random.normal()
    S_prev = euler_prices[-1]

    S_next = S_prev + mu * S_prev * dt + sigma * S_prev * np.sqrt(dt) * Z
    euler_prices.append(S_next)

milstein_prices = [S0]

for t in range(T):
    Z = np.random.normal()
    S_prev = milstein_prices[-1]

    S_next = (
        S_prev
        + mu * S_prev * dt
        + sigma * S_prev * np.sqrt(dt) * Z
        + 0.5 * (sigma**2) * S_prev * dt * (Z**2 - 1)
    )

    milstein_prices.append(S_next)

import numpy as np

euler_prices = np.array(euler_prices)
milstein_prices = np.array(milstein_prices)

avg_prices = (euler_prices + milstein_prices) / 2

print(avg_prices)

import matplotlib.pyplot as plt

plt.plot(euler_prices, label="Euler")
plt.plot(milstein_prices, label="Milstein")
plt.plot(avg_prices, label="Average", linewidth=3)

plt.legend()
plt.title("Final Prediction (Average of Models)")
plt.show()

import numpy as np

avg_euler = np.mean(euler_prices)

print("Average Euler Prediction:", avg_euler)

